#!/bin/sh
# lib/origin-trust-gate.sh — gh-flow:issue Step 1.5 (dEitY719/gh-flow-skills#36):
# classify who WROTE the issue, so a chain that treats the issue body as its
# implementation spec knows whether that spec came from a harness this family
# trusts.
#
# EXECUTE it, never source it — the verdict is stdout, not an export:
#
#   body=$(GH_HOST="$TARGET_HOST" gh issue view <N> --repo "$TARGET_REPO" \
#       --json body --jq .body 2>/dev/null) || body=''
#   verdict=$(printf '%s\n' "$body" | sh "$gate")   # "<harness> <verdict>"
#
# The `|| body=''` is the fail-closed arm (NF-2): a body this script cannot
# read parses as `none`, which is never trusted, so a broken fetch lands on
# the review path instead of waving the issue through.
#
# Input   the issue body on stdin.
# Reads   GH_TRUSTED_HARNESSES — space-separated, family-wide (the same name
#         gh-issue-skills#44 D-3 settled on, NOT a gh-flow-private spelling).
#         Unset means the default set `claude codex`; set-but-empty means an
#         empty set, i.e. review everything, because an explicit override is
#         honoured as written.
# Output  one line, `<harness> <verdict>`, with verdict `trusted` | `review`.
#         `<harness>` is lowercased, and `none` whenever no well-formed origin
#         line was found.
# Exit    0 on both verdicts — `review` is a routing decision, not an error.
#         The BLOCK exit 2 belongs to the reviewing step, not to this parser.
#
# Origin-line format is owned by dEitY719/gh-issue-skills#43 — a standalone
# line at the bottom of the issue body:
#
#   Generated by Harness(<harness>) and LLM(<model>)
#
# `LLM(...)` is parsed only to anchor the line; v1 never branches on the model
# name (D-3). The LAST match wins (F-1), so an issue quoting an older card's
# footer is still classified by its own.
#
# Self-check: lib/origin-trust-gate.selfcheck.sh

# `tr -d '\r'` first: `gh issue view --json body` hands back the CRLF the
# GitHub web editor stores, and a trailing CR defeats the end-of-line anchor.
_otg_harness=$(
    tr -d '\r' \
        | sed -n 's/^Generated by Harness(\(.*\)) and LLM(.*)$/\1/p' \
        | tail -n 1 \
        | tr '[:upper:]' '[:lower:]'
)
[ -n "$_otg_harness" ] || _otg_harness=none

_otg_verdict=review
if [ "$_otg_harness" != none ]; then
    # Unquoted on purpose — the trust set is space-separated. `-` not `:-`,
    # so GH_TRUSTED_HARNESSES="" is an empty set rather than the default one.
    # shellcheck disable=SC2086
    for _otg_t in ${GH_TRUSTED_HARNESSES-claude codex}; do
        [ "$_otg_harness" = "$_otg_t" ] || continue
        _otg_verdict=trusted
        break
    done
fi

printf '%s %s\n' "$_otg_harness" "$_otg_verdict"
