#!/usr/bin/env bash
# Self-check for lib/origin-trust-gate.sh. No framework, no fixtures:
#
#   bash skills/issue/lib/origin-trust-gate.selfcheck.sh
#
# The issue body arrives on stdin, so every case is a heredoc — no network,
# no gh auth, no repo state. Exits non-zero on the first behaviour that
# regressed.
set -u

# shellcheck disable=SC1091  # path is resolved at runtime
. "$(dirname -- "$0")/selfcheck-common.sh"
TARGET="$ROOT/skills/issue/lib/origin-trust-gate.sh"

# The ambient shell may already export the family-wide trust set — unset it so
# the DEFAULT is what the unset-case assertions actually exercise.
unset GH_TRUSTED_HARNESSES

gate() { sh "$TARGET"; }  # body on stdin, "<harness> <verdict>" on stdout

# 1. Default trust set: claude and codex are trusted, case-normalised.
chk "claude trusted" \
    "$(printf 'body\n\nGenerated by Harness(claude) and LLM(opus)\n' | gate)" \
    "claude trusted"
chk "codex trusted" \
    "$(printf 'Generated by Harness(codex) and LLM(gpt-5)\n' | gate)" \
    "codex trusted"
chk "uppercase normalised" \
    "$(printf 'Generated by Harness(CLAUDE) and LLM(Opus)\n' | gate)" \
    "claude trusted"

# 2. Every other harness goes to the review path (allow-list, D-5).
chk "opencode reviewed" \
    "$(printf 'Generated by Harness(opencode) and LLM(qwen3)\n' | gate)" \
    "opencode review"

# 3. Unknown origin is untrusted (D-2, fail-closed): literal none, an empty
#    capture, a line that never appeared, and a malformed one.
chk "none reviewed" \
    "$(printf 'Generated by Harness(none) and LLM(none)\n' | gate)" \
    "none review"
chk "empty capture reviewed" \
    "$(printf 'Generated by Harness() and LLM()\n' | gate)" \
    "none review"
chk "missing line reviewed" \
    "$(printf 'a legacy issue body\nwith no origin line\n' | gate)" \
    "none review"
chk "malformed line reviewed" \
    "$(printf 'Generated by Harness(claude and LLM(opus)\n' | gate)" \
    "none review"
chk "empty body reviewed (NF-2 fetch failure)" \
    "$(printf '' | gate)" \
    "none review"

# 4. The origin line must be the WHOLE line — a quoted or indented mention
#    inside prose is not an origin claim.
chk "indented mention ignored" \
    "$(printf '  Generated by Harness(claude) and LLM(opus)\n' | gate)" \
    "none review"

# 5. Two origin lines: the LAST one wins (F-1).
chk "last match wins" \
    "$(printf 'Generated by Harness(claude) and LLM(opus)\nquoted above\nGenerated by Harness(agy) and LLM(glm3)\n' | gate)" \
    "agy review"

# 6. CRLF bodies — what `gh issue view --json body` actually returns for an
#    issue authored through the web UI. Without the strip, the trailing \r
#    breaks the anchor and a trusted issue silently becomes a reviewed one.
chk "CRLF body still parses" \
    "$(printf 'body\r\n\r\nGenerated by Harness(claude) and LLM(opus)\r\n' | gate)" \
    "claude trusted"

# 7. GH_TRUSTED_HARNESSES overrides the default set (F-2, D-4).
chk "override narrows the set" \
    "$(GH_TRUSTED_HARNESSES="claude" gate <<<'Generated by Harness(codex) and LLM(gpt-5)')" \
    "codex review"
chk "override widens the set" \
    "$(GH_TRUSTED_HARNESSES="claude codex agy" gate <<<'Generated by Harness(agy) and LLM(glm3)')" \
    "agy trusted"
chk "empty override trusts nobody" \
    "$(GH_TRUSTED_HARNESSES="" gate <<<'Generated by Harness(claude) and LLM(opus)')" \
    "claude review"
chk "override cannot trust the unknown origin" \
    "$(GH_TRUSTED_HARNESSES="claude none" gate <<<'Generated by Harness(none) and LLM(none)')" \
    "none review"

# 8. A glob metacharacter in the harness value is matched literally, not as a
#    pattern. The membership test is a `case`, and the issue body is written by
#    whoever filed the issue: if `$_otg_harness` were spliced into that pattern
#    unquoted, `Harness(*)` would match every trust set and walk straight
#    through the gate. Fail-open at a trust boundary, and silent.
chk "glob harness is not a wildcard" \
    "$(printf 'Generated by Harness(*) and LLM(x)\n' | gate)" \
    "* review"
chk "single-char glob is not a wildcard" \
    "$(printf 'Generated by Harness(?laude) and LLM(x)\n' | gate)" \
    "?laude review"
chk "prefix is not a member" \
    "$(printf 'Generated by Harness(claudex) and LLM(x)\n' | gate)" \
    "claudex review"

# 9. Exit 0 on BOTH verdicts (header contract): `review` is a routing decision,
#    not an error, and the BLOCK exit 2 belongs to the reviewing step. Every
#    assertion above runs inside `$(...)`, which swallows the status — so the
#    contract needs its own case or a regression here would stay silent.
printf 'Generated by Harness(claude) and LLM(opus)\n' | gate >/dev/null
chk "trusted verdict: exit 0" "$?" "0"
printf 'Generated by Harness(hermes) and LLM(glm3)\n' | gate >/dev/null
chk "review verdict: exit 0" "$?" "0"

exit "$FAIL"
